# # mkdir LC1_Two_Sum
# # mkdir LC2_Add_Two_Numbers
# mkdir LC3_Longest_Substring_Without_Repeating_Characters
# mkdir LC4_Median_Of_Two_Sorted_Arrays
# mkdir LC5_Longest_Palindromic_Substring
# mkdir LC6_Zigzag_Conversion
# mkdir LC7_Reverse_Integer
# mkdir LC8_String_To_Integer_Atoi
# mkdir LC9_Palindrome_Number
# mkdir LC10_Regular_Expression_Matching
# mkdir LC11_Container_With_Most_Water
# mkdir LC12_Integer_To_Roman
# mkdir LC13_Roman_To_Integer
# mkdir LC14_Longest_Common_Prefix
# mkdir LC15_3sum
# mkdir LC16_3sum_Closest
# mkdir LC17_Letter_Combinations_Of_A_Phone_Number
# mkdir LC18_4sum
# mkdir LC19_Remove_Nth_Node_From_End_Of_List
# mkdir LC20_Valid_Parentheses
# # mkdir LC21_Merge_Two_Sorted_Lists
# mkdir LC22_Generate_Parentheses
# # mkdir LC23_Merge_K_Sorted_Lists
# mkdir LC24_Swap_Nodes_In_Pairs
# mkdir LC25_Reverse_Nodes_In_K_Group
# mkdir LC26_Remove_Duplicates_From_Sorted_Array
# mkdir LC27_Remove_Element
# mkdir LC28_Find_The_Index_Of_The_First_Occurrence_In_A_String
# mkdir LC29_Divide_Two_Integers
# mkdir LC30_Substring_With_Concatenation_Of_All_Words
# mkdir LC31_Next_Permutation
# mkdir LC32_Longest_Valid_Parentheses
# # mkdir LC33_Search_In_Rotated_Sorted_Array
# mkdir LC34_Find_First_And_Last_Position_Of_Element_In_Sorted_Array
# mkdir LC35_Search_Insert_Position
# mkdir LC36_Valid_Sudoku
# mkdir LC37_Sudoku_Solver
# mkdir LC38_Count_And_Say
# mkdir LC39_Combination_Sum
# mkdir LC40_Combination_Sum_Ii
# mkdir LC41_First_Missing_Positive
# mkdir LC42_Trapping_Rain_Water
# mkdir LC43_Multiply_Strings
# mkdir LC44_Wildcard_Matching
# mkdir LC45_Jump_Game_Ii
# mkdir LC46_Permutations
# mkdir LC47_Permutations_Ii
# mkdir LC48_Rotate_Image
# mkdir LC49_Group_Anagrams
# mkdir LC50_Powx_N
# mkdir LC51_N_Queens
# mkdir LC54_N_Queens_Ii
# # mkdir LC53_Maximum_Subarray
# mkdir LC54_Spiral_Matrix
# # mkdir LC55_Jump_Game
# mkdir LC56_Merge_Intervals
# mkdir LC57_Insert_Interval
# mkdir LC58_Length_Of_Last_Word
# mkdir LC59_Spiral_Matrix_Ii
# mkdir LC60_Permutation_Sequence
# mkdir LC61_Rotate_List
# mkdir LC62_Unique_Paths
# mkdir LC63_Unique_Paths_Ii
# mkdir LC64_Minimum_Path_Sum
# mkdir LC65_Valid_Number
# mkdir LC66_Plus_One
# mkdir LC67_Add_Binary
# mkdir LC68_Text_Justification
# mkdir LC69_Sqrtx
# mkdir LC70_Climbing_Stairs
# mkdir LC71_Simplify_Path
# mkdir LC72_Edit_Distance
# mkdir LC73_Set_Matrix_Zeroes
# mkdir LC74_Search_A_2d_Matrix
# mkdir LC75_Sort_Colors
# mkdir LC76_Minimum_Window_Substring
# mkdir LC77_Combinations
# mkdir LC78_Subsets
# mkdir LC79_Word_Search
# mkdir LC80_Remove_Duplicates_From_Sorted_Array_Ii
# mkdir LC81_Search_In_Rotated_Sorted_Array_Ii
# mkdir LC82_Remove_Duplicates_From_Sorted_List_Ii
# mkdir LC83_Remove_Duplicates_From_Sorted_List
# mkdir LC84_Largest_Rectangle_In_Histogram
# mkdir LC85_Maximal_Rectangle
# mkdir LC86_Partition_List
# mkdir LC87_Scramble_String
# mkdir LC88_Merge_Sorted_Array
# mkdir LC89_Gray_Code
# mkdir LC90_Subsets_Ii
# mkdir LC91_Decode_Ways
# mkdir LC92_Reverse_Linked_List_Ii
# mkdir LC93_Restore_Ip_Addresses
# mkdir LC94_Binary_Tree_Inorder_Traversal
# mkdir LC95_Unique_Binary_Search_Trees_Ii
# mkdir LC96_Unique_Binary_Search_Trees
# mkdir LC97_Interleaving_String
# mkdir LC98_Validate_Binary_Search_Tree
# mkdir LC99_Recover_Binary_Search_Tree
# mkdir LC100_Same_Tree
mkdir LC101_Symmetric_Tree
mkdir LC102_Binary_Tree_Level_Order_Traversal
mkdir LC103_Binary_Tree_Zigzag_Level_Order_Traversal
mkdir LC104_Maximum_Depth_Of_Binary_Tree
mkdir LC105_Construct_Binary_Tree_From_Preorder_And_Inorder_Traversal
mkdir LC106_Construct_Binary_Tree_From_Inorder_And_Postorder_Traversal
mkdir LC107_Binary_Tree_Level_Order_Traversal_Ii
mkdir LC108_Convert_Sorted_Array_To_Binary_Search_Tree
mkdir LC109_Convert_Sorted_List_To_Binary_Search_Tree
mkdir LC110_Balanced_Binary_Tree
mkdir LC111_Minimum_Depth_Of_Binary_Tree
mkdir LC112_Path_Sum
mkdir LC113_Path_Sum_Ii
mkdir LC114_Flatten_Binary_Tree_To_Linked_List
mkdir LC115_Distinct_Subsequences
mkdir LC116_Populating_Next_Right_Pointers_In_Each_Node
mkdir LC117_Populating_Next_Right_Pointers_In_Each_Node_Ii
mkdir LC118_Pascals_Triangle
mkdir LC119_Pascals_Triangle_Ii
mkdir LC120_Triangle
mkdir LC121_Best_Time_To_Buy_And_Sell_Stock
mkdir LC122_Best_Time_To_Buy_And_Sell_Stock_Ii
mkdir LC123_Best_Time_To_Buy_And_Sell_Stock_Iii
mkdir LC124_Binary_Tree_Maximum_Path_Sum
mkdir LC125_Valid_Palindrome
mkdir LC126_Word_Ladder_Ii
mkdir LC127_Word_Ladder
mkdir LC128_Longest_Consecutive_Sequence
mkdir LC129_Sum_Root_To_Leaf_Numbers
mkdir LC130_Surrounded_Regions
mkdir LC131_Palindrome_Partitioning
mkdir LC132_Palindrome_Partitioning_Ii
mkdir LC133_Clone_Graph
mkdir LC134_Gas_Station
mkdir LC135_Candy
mkdir LC136_Single_Number
mkdir LC137_Single_Number_Ii
mkdir LC138_Copy_List_With_Random_Pointer
mkdir LC139_Word_Break
mkdir LC140_Word_Break_Ii
mkdir LC141_Linked_List_Cycle
mkdir LC142_Linked_List_Cycle_Ii
mkdir LC143_Reorder_List
mkdir LC144_Binary_Tree_Preorder_Traversal
mkdir LC145_Binary_Tree_Postorder_Traversal
mkdir LC146_Lru_Cache
mkdir LC147_Insertion_Sort_List
mkdir LC148_Sort_List
mkdir LC149_Max_Points_On_A_Line
mkdir LC150_Evaluate_Reverse_Polish_Notation
mkdir LC151_Reverse_Words_In_A_String
mkdir LC152_Maximum_Product_Subarray
mkdir LC153_Find_Minimum_In_Rotated_Sorted_Array
mkdir LC154_Find_Minimum_In_Rotated_Sorted_Array_Ii
mkdir LC155_Min_Stack
mkdir LC156_Binary_Tree_Upside_Down
mkdir LC157_Read_N_Characters_Given_Read4
mkdir LC158_Read_N_Characters_Given_Read4_Ii_Call_Multiple_Times
mkdir LC159_Longest_Substring_With_At_Most_Two_Distinct_Characters
mkdir LC160_Intersection_Of_Two_Linked_Lists
mkdir LC161_One_Edit_Distance
mkdir LC162_Find_Peak_Element
mkdir LC163_Missing_Ranges
mkdir LC164_Maximum_Gap
mkdir LC165_Compare_Version_Numbers
mkdir LC166_Fraction_To_Recurring_Decimal
mkdir LC167_Two_Sum_Ii_Input_Array_Is_Sorted
mkdir LC168_Excel_Sheet_Column_Title
mkdir LC169_Majority_Element
mkdir LC170_Two_Sum_Iii_Data_Structure_Design
mkdir LC171_Excel_Sheet_Column_Number
mkdir LC172_Factorial_Trailing_Zeroes
mkdir LC173_Binary_Search_Tree_Iterator
mkdir LC174_Dungeon_Game
mkdir LC175_Combine_Two_Tables
mkdir LC176_Second_Highest_Salary
mkdir LC177_Nth_Highest_Salary
mkdir LC178_Rank_Scores
mkdir LC179_Largest_Number
mkdir LC180_Consecutive_Numbers
mkdir LC181_Employees_Earning_More_Than_Their_Managers
mkdir LC182_Duplicate_Emails
mkdir LC183_Customers_Who_Never_Order
mkdir LC184_Department_Highest_Salary
mkdir LC185_Department_Top_Three_Salaries
mkdir LC186_Reverse_Words_In_A_String_Ii
mkdir LC187_Repeated_Dna_Sequences
mkdir LC188_Best_Time_To_Buy_And_Sell_Stock_Iv
mkdir LC189_Rotate_Array
mkdir LC190_Reverse_Bits
mkdir LC191_Number_Of_1_Bits
mkdir LC192_Word_Frequency
mkdir LC193_Valid_Phone_Numbers
mkdir LC194_Transpose_File
mkdir LC195_Tenth_Line
mkdir LC196_Delete_Duplicate_Emails
mkdir LC197_Rising_Temperature
mkdir LC198_House_Robber
mkdir LC199_Binary_Tree_Right_Side_View
mkdir LC200_Number_Of_Islands
mkdir LC201_Bitwise_And_Of_Numbers_Range
mkdir LC202_Happy_Number
mkdir LC203_Remove_Linked_List_Elements
mkdir LC204_Count_Primes
mkdir LC205_Isomorphic_Strings
mkdir LC206_Reverse_Linked_List
mkdir LC207_Course_Schedule
mkdir LC208_Implement_Trie_Prefix_Tree
mkdir LC209_Minimum_Size_Subarray_Sum
# mkdir LC210_Course_Schedule_Ii
mkdir LC211_Design_Add_And_Search_Words_Data_Structure
# mkdir LC212_Word_Search_Ii
mkdir LC213_House_Robber_Ii
mkdir LC214_Shortest_Palindrome
mkdir LC215_Kth_Largest_Element_In_An_Array
mkdir LC216_Combination_Sum_Iii
mkdir LC217_Contains_Duplicate
mkdir LC218_The_Skyline_Problem
mkdir LC219_Contains_Duplicate_Ii
mkdir LC220_Contains_Duplicate_Iii
mkdir LC221_Maximal_Square
mkdir LC222_Count_Complete_Tree_Nodes
mkdir LC223_Rectangle_Area
mkdir LC224_Basic_Calculator
mkdir LC225_Implement_Stack_Using_Queues
mkdir LC226_Invert_Binary_Tree
mkdir LC227_Basic_Calculator_Ii
mkdir LC228_Summary_Ranges
mkdir LC229_Majority_Element_Ii
mkdir LC230_Kth_Smallest_Element_In_A_Bst
mkdir LC231_Power_Of_Two
mkdir LC232_Implement_Queue_Using_Stacks
mkdir LC233_Number_Of_Digit_One
mkdir LC234_Palindrome_Linked_List
mkdir LC235_Lowest_Common_Ancestor_Of_A_Binary_Search_Tree
mkdir LC236_Lowest_Common_Ancestor_Of_A_Binary_Tree
mkdir LC237_Delete_Node_In_A_Linked_List
mkdir LC238_Product_Of_Array_Except_Self
mkdir LC239_Sliding_Window_Maximum
mkdir LC240_Search_A_2d_Matrix_Ii
mkdir LC241_Different_Ways_To_Add_Parentheses
mkdir LC242_Valid_Anagram
mkdir LC243_Shortest_Word_Distance
mkdir LC244_Shortest_Word_Distance_Ii
mkdir LC245_Shortest_Word_Distance_Iii
mkdir LC246_Strobogrammatic_Number
mkdir LC247_Strobogrammatic_Number_Ii
mkdir LC248_Strobogrammatic_Number_Iii
mkdir LC249_Group_Shifted_Strings
mkdir LC250_Count_Univalue_Subtrees
mkdir LC251_Flatten_2d_Vector
mkdir LC252_Meeting_Rooms
mkdir LC253_Meeting_Rooms_Ii
mkdir LC254_Factor_Combinations
mkdir LC255_Verify_Preorder_Sequence_In_Binary_Search_Tree
mkdir LC256_Paint_House
mkdir LC257_Binary_Tree_Paths
mkdir LC258_Add_Digits
mkdir LC259_3sum_Smaller
mkdir LC260_Single_Number_Iii
# mkdir LC261_Graph_Valid_Tree
mkdir LC262_Trips_And_Users
mkdir LC263_Ugly_Number
mkdir LC264_Ugly_Number_Ii
mkdir LC265_Paint_House_Ii
mkdir LC266_Palindrome_Permutation
mkdir LC267_Palindrome_Permutation_Ii
mkdir LC268_Missing_Number
mkdir LC269_Alien_Dictionary
mkdir LC270_Closest_Binary_Search_Tree_Value
mkdir LC271_Encode_And_Decode_Strings
mkdir LC272_Closest_Binary_Search_Tree_Value_Ii
mkdir LC273_Integer_To_English_Words
mkdir LC274_H_Index
mkdir LC275_H_Index_Ii
mkdir LC276_Paint_Fence
mkdir LC277_Find_The_Celebrity
mkdir LC278_First_Bad_Version
mkdir LC279_Perfect_Squares
mkdir LC280_Wiggle_Sort
mkdir LC281_Zigzag_Iterator
mkdir LC282_Expression_Add_Operators
mkdir LC283_Move_Zeroes
mkdir LC284_Peeking_Iterator
mkdir LC285_Inorder_Successor_In_Bst
mkdir LC286_Walls_And_Gates
mkdir LC287_Find_The_Duplicate_Number
mkdir LC288_Unique_Word_Abbreviation
mkdir LC289_Game_Of_Life
mkdir LC290_Word_Pattern
# mkdir LC291_Word_Pattern_Ii
mkdir LC292_Nim_Game
mkdir LC293_Flip_Game
mkdir LC294_Flip_Game_Ii
mkdir LC295_Find_Median_From_Data_Stream
mkdir LC296_Best_Meeting_Point
mkdir LC297_Serialize_And_Deserialize_Binary_Tree
mkdir LC298_Binary_Tree_Longest_Consecutive_Sequence
mkdir LC299_Bulls_And_Cows
mkdir LC300_Longest_Increasing_Subsequence
# mkdir LC301_Remove_Invalid_Parentheses
mkdir LC302_Smallest_Rectangle_Enclosing_Black_Pixels
mkdir LC303_Range_Sum_Query_Immutable
# mkdir LC304_Range_Sum_Query_2d_Immutable
mkdir LC305_Number_Of_Islands_Ii
mkdir LC306_Additive_Number
mkdir LC307_Range_Sum_Query_Mutable
mkdir LC308_Range_Sum_Query_2d_Mutable
mkdir LC309_Best_Time_To_Buy_And_Sell_Stock_With_Cooldown
mkdir LC310_Minimum_Height_Trees
mkdir LC311_Sparse_Matrix_Multiplication
mkdir LC312_Burst_Balloons
mkdir LC313_Super_Ugly_Number
mkdir LC314_Binary_Tree_Vertical_Order_Traversal
mkdir LC315_Count_Of_Smaller_Numbers_After_Self
mkdir LC316_Remove_Duplicate_Letters
mkdir LC317_Shortest_Distance_From_All_Buildings
mkdir LC318_Maximum_Product_Of_Word_Lengths
mkdir LC319_Bulb_Switcher
mkdir LC320_Generalized_Abbreviation
mkdir LC321_Create_Maximum_Number
mkdir LC322_Coin_Change
mkdir LC323_Number_Of_Connected_Components_In_An_Undirected_Graph
mkdir LC324_Wiggle_Sort_Ii
mkdir LC325_Maximum_Size_Subarray_Sum_Equals_K
mkdir LC326_Power_Of_Three
mkdir LC327_Count_Of_Range_Sum
mkdir LC328_Odd_Even_Linked_List
mkdir LC329_Longest_Increasing_Path_In_A_Matrix
# mkdir LC330_Patching_Array
mkdir LC331_Verify_Preorder_Serialization_Of_A_Binary_Tree
mkdir LC332_Reconstruct_Itinerary
mkdir LC333_Largest_Bst_Subtree
mkdir LC334_Increasing_Triplet_Subsequence
mkdir LC335_Self_Crossing
mkdir LC336_Palindrome_Pairs
mkdir LC337_House_Robber_Iii
mkdir LC338_Counting_Bits
mkdir LC339_Nested_List_Weight_Sum
mkdir LC340_Longest_Substring_With_At_Most_K_Distinct_Characters
mkdir LC341_Flatten_Nested_List_Iterator
mkdir LC342_Power_Of_Four
mkdir LC343_Integer_Break
mkdir LC344_Reverse_String
mkdir LC345_Reverse_Vowels_Of_A_String
mkdir LC346_Moving_Average_From_Data_Stream
mkdir LC347_Top_K_Frequent_Elements
mkdir LC348_Design_Tic_Tac_Toe
mkdir LC349_Intersection_Of_Two_Arrays
mkdir LC350_Intersection_Of_Two_Arrays_Ii
mkdir LC351_Android_Unlock_Patterns
mkdir LC352_Data_Stream_As_Disjoint_Intervals
mkdir LC353_Design_Snake_Game
mkdir LC354_Russian_Doll_Envelopes
mkdir LC355_Design_Twitter
mkdir LC356_Line_Reflection
mkdir LC357_Count_Numbers_With_Unique_Digits
mkdir LC358_Rearrange_String_K_Distance_Apart
mkdir LC359_Logger_Rate_Limiter
mkdir LC360_Sort_Transformed_Array
mkdir LC361_Bomb_Enemy
mkdir LC362_Design_Hit_Counter
mkdir LC363_Max_Sum_Of_Rectangle_No_Larger_Than_K
mkdir LC364_Nested_List_Weight_Sum_Ii
mkdir LC365_Water_And_Jug_Problem
mkdir LC366_Find_Leaves_Of_Binary_Tree
mkdir LC367_Valid_Perfect_Square
mkdir LC368_Largest_Divisible_Subset
mkdir LC369_Plus_One_Linked_List
mkdir LC370_Range_Addition
mkdir LC371_Sum_Of_Two_Integers
mkdir LC372_Super_Pow
mkdir LC373_Find_K_Pairs_With_Smallest_Sums
mkdir LC374_Guess_Number_Higher_Or_Lower
mkdir LC375_Guess_Number_Higher_Or_Lower_Ii
mkdir LC376_Wiggle_Subsequence
mkdir LC377_Combination_Sum_Iv
mkdir LC378_Kth_Smallest_Element_In_A_Sorted_Matrix
mkdir LC379_Design_Phone_Directory
# mkdir LC380_Insert_Delete_Getrandom_O1
mkdir LC381_Insert_Delete_Getrandom_O1_Duplicates_Allowed
mkdir LC382_Linked_List_Random_Node
mkdir LC383_Ransom_Note
mkdir LC384_Shuffle_An_Array
mkdir LC385_Mini_Parser
mkdir LC386_Lexicographical_Numbers
mkdir LC387_First_Unique_Character_In_A_String
mkdir LC388_Longest_Absolute_File_Path
mkdir LC389_Find_The_Difference
mkdir LC390_Elimination_Game
mkdir LC391_Perfect_Rectangle
mkdir LC392_Is_Subsequence
mkdir LC393_Utf_8_Validation
# mkdir LC394_Decode_String
mkdir LC395_Longest_Substring_With_At_Least_K_Repeating_Characters
mkdir LC396_Rotate_Function
mkdir LC397_Integer_Replacement
mkdir LC398_Random_Pick_Index
mkdir LC399_Evaluate_Division
mkdir LC400_Nth_Digit
mkdir LC401_Binary_Watch
mkdir LC402_Remove_K_Digits
mkdir LC403_Frog_Jump
mkdir LC404_Sum_Of_Left_Leaves
mkdir LC405_Convert_A_Number_To_Hexadecimal
mkdir LC406_Queue_Reconstruction_By_Height
mkdir LC407_Trapping_Rain_Water_Ii
mkdir LC408_Valid_Word_Abbreviation
mkdir LC409_Longest_Palindrome
mkdir LC410_Split_Array_Largest_Sum
mkdir LC411_Minimum_Unique_Word_Abbreviation
mkdir LC412_Fizz_Buzz
mkdir LC413_Arithmetic_Slices
mkdir LC414_Third_Maximum_Number
mkdir LC415_Add_Strings
mkdir LC416_Partition_Equal_Subset_Sum
mkdir LC417_Pacific_Atlantic_Water_Flow
mkdir LC418_Sentence_Screen_Fitting
mkdir LC419_Battleships_In_A_Board
mkdir LC420_Strong_Password_Checker
mkdir LC421_Maximum_Xor_Of_Two_Numbers_In_An_Array
mkdir LC422_Valid_Word_Square
mkdir LC423_Reconstruct_Original_Digits_From_English
mkdir LC424_Longest_Repeating_Character_Replacement
mkdir LC425_Word_Squares
mkdir LC426_Convert_Binary_Search_Tree_To_Sorted_Doubly_Linked_List
mkdir LC427_Construct_Quad_Tree
mkdir LC428_Serialize_And_Deserialize_N_Ary_Tree
mkdir LC429_N_Ary_Tree_Level_Order_Traversal
mkdir LC430_Flatten_A_Multilevel_Doubly_Linked_List
mkdir LC431_Encode_N_Ary_Tree_To_Binary_Tree
# mkdir LC432_All_Oone_Data_Structure
mkdir LC433_Minimum_Genetic_Mutation
# mkdir LC434_Number_Of_Segments_In_A_String
mkdir LC435_Non_Overlapping_Intervals
mkdir LC436_Find_Right_Interval
mkdir LC437_Path_Sum_Iii
# mkdir LC438_Find_All_Anagrams_In_A_String
mkdir LC439_Ternary_Expression_Parser
mkdir LC440_K_Th_Smallest_In_Lexicographical_Order
mkdir LC441_Arranging_Coins
mkdir LC442_Find_All_Duplicates_In_An_Array
mkdir LC443_String_Compression
mkdir LC444_Sequence_Reconstruction
mkdir LC445_Add_Two_Numbers_Ii
mkdir LC446_Arithmetic_Slices_Ii_Subsequence
mkdir LC447_Number_Of_Boomerangs
mkdir LC448_Find_All_Numbers_Disappeared_In_An_Array
mkdir LC449_Serialize_And_Deserialize_Bst
mkdir LC450_Delete_Node_In_A_Bst
mkdir LC451_Sort_Characters_By_Frequency
mkdir LC452_Minimum_Number_Of_Arrows_To_Burst_Balloons
mkdir LC453_Minimum_Moves_To_Equal_Array_Elements
mkdir LC454_4sum_Ii
mkdir LC455_Assign_Cookies
mkdir LC456_132_Pattern
mkdir LC457_Circular_Array_Loop
mkdir LC458_Poor_Pigs
mkdir LC459_Repeated_Substring_Pattern
mkdir LC460_Lfu_Cache
mkdir LC461_Hamming_Distance
mkdir LC462_Minimum_Moves_To_Equal_Array_Elements_Ii
mkdir LC463_Island_Perimeter
mkdir LC464_Can_I_Win
mkdir LC465_Optimal_Account_Balancing
mkdir LC466_Count_The_Repetitions
mkdir LC467_Unique_Substrings_In_Wraparound_String
mkdir LC468_Validate_Ip_Address
mkdir LC469_Convex_Polygon
mkdir LC470_Implement_Rand10_Using_Rand7
mkdir LC471_Encode_String_With_Shortest_Length
mkdir LC472_Concatenated_Words
mkdir LC473_Matchsticks_To_Square
mkdir LC474_Ones_And_Zeroes
mkdir LC475_Heaters
mkdir LC476_Number_Complement
mkdir LC477_Total_Hamming_Distance
mkdir LC478_Generate_Random_Point_In_A_Circle
mkdir LC479_Largest_Palindrome_Product
mkdir LC480_Sliding_Window_Median
mkdir LC481_Magical_String
mkdir LC482_License_Key_Formatting
mkdir LC483_Smallest_Good_Base
mkdir LC484_Find_Permutation
mkdir LC485_Max_Consecutive_Ones
mkdir LC486_Predict_The_Winner
mkdir LC487_Max_Consecutive_Ones_Ii
mkdir LC488_Zuma_Game
mkdir LC489_Robot_Room_Cleaner
mkdir LC490_The_Maze
mkdir LC491_Non_Decreasing_Subsequences
mkdir LC492_Construct_The_Rectangle
mkdir LC493_Reverse_Pairs
mkdir LC494_Target_Sum
mkdir LC495_Teemo_Attacking
mkdir LC496_Next_Greater_Element_I
mkdir LC497_Random_Point_In_Non_Overlapping_Rectangles
mkdir LC498_Diagonal_Traverse
mkdir LC499_The_Maze_Iii
mkdir LC500_Keyboard_Row






# mkdir LC1235_Maximum_Profit_In_Job_Scheduling
# mkdir LC1248_Count_Number_Of_Nice_Subarrays
# mkdir LC1639_Number_Of_Ways_To_Form_A_Target_String_Given_A_Dictionary
# mkdir LC1698_Number_Of_Distinct_Substrings_In_A_String
# mkdir LC1960_Maximum_Product_Of_The_Length_Of_Two_Palindromic_Substrings
# mkdir LC2002_Maximum_Product_Of_The_Length_Of_Two_Palindromic_Subsequences
# mkdir LC2050_Parallel_Courses_III
# mkdir LC2062_Count_Vowel_Substrings_Of_A_String
# mkdir LC210_Course_Schedule_II
# mkdir LC212_Word_Search_II
# mkdir LC21_Merge_Two_Sorted_Lists
# mkdir LC23_Merge_K_Sorted_Lists
# mkdir LC261_Graph_Valid_Tree
# mkdir LC2742_Painting_The_Walls
# mkdir LC2856_Minimum_Array_Length_After_Pair_Removals
# mkdir LC291_Word_Pattern_II
# mkdir LC301_Remove_Invalid_Parentheses
# mkdir LC304_Range_Sum_Query_2D_Immutable
# mkdir LC330_Patching_Array
# mkdir LC33_Search_In_Rotated_Sorted_Array
# mkdir LC380_Insert_Delete_GetRandom_O_1
# mkdir LC394_Decode_String
# mkdir LC432_All_Oone_Data_Structure
# mkdir LC434_Number_Of_Segments_In_A_String
# mkdir LC438_Find_All_Anagrams_In_A_String
# mkdir LC516_Longest_Palindromic_Subsequence
# mkdir LC528_Random_Pick_With_Weight
# mkdir LC53_Maximum_Subarray
# mkdir LC542_01_Matrix
# mkdir LC55_Jump_Game
# mkdir LC588_Design_In_Memory_File_System
# mkdir LC905_Sort_Array_By_Parity
# mkdir LC910_Smallest_Range_II
# mkdir LC981_Time_Based_Key_Value_Store



